import './globals.css'

import 'bootstrap/dist/css/bootstrap.css'

import {Poppins} from 'next/font/google'

import NavBar from './components/navbar';

const poppins = Poppins({

  weight: ['400', '700'],
  subsets: ['latin']

});

export const metadata = {
  title: 'Simple Next',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossOrigin="anonymous"
        />
      </head>
      <body className={poppins.className}>
        <NavBar />
        <section className='bg-light'>
          {children}
        </section>
      </body>
    </html>
  )
}
